name: Update RST File with Custom Label

on:
  pull_request:
    types:
      - opened  # Trigger the workflow when a pull request is opened

jobs:
  update-label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Custom Label
        run: |
          # Use a custom script or command to update the RST file with the desired label value
          # For example, you can use sed or a programming language of your choice.
          # Make sure to store the updated file in the repository.

          # Example using sed to update a label in an RST file:
          sed -i 's/CustomLabel: .*/CustomLabel: NewValue/' req.rst

        # Commit and push the changes back to the branch
        run: |
          git config --global user.email "winvicky1998@gmail.com"
          git config --global user.name "Vignesh-VIT"
          git req.rst
          git commit -m "Update RST file with custom label"
          git push
