name: Create Folders Based on Labels

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  create-folders:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Folders
      run: |
        labels=$(gh pr view ${{ github.event.pull_request.number }} --json labels -q .labels)
        for label in $labels; do
          folder_name=$(echo $label | tr '[:upper:]' '[:lower:]' | sed 's/ /_/g')
          mkdir -p $folder_name
        done
      env:
        GITHUB_TOKEN: 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
