name: Create Folder based on Labels

on:
  pull_request:
    types:
      - opened

jobs:
  create-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Folder
        run: |
          # Extract the labels from the pull request
          labels=$(jq -r '.pull_request.labels[].name' "$GITHUB_EVENT_PATH")

          # Iterate through the labels and create folders
          for label in $labels; do
            mkdir -p "$label"
          done
        shell: bash

      - name: Commit and Push Changes
        run: |
          git config --global user.email "winvicky1998@gmail.com"
          git config --global user.name "Vignesh-VIT"
          git add .
          git commit -m "Create folders based on labels"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
